--USE postgres;

---------схемы базы--------------------------------------------------------
---------------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS stage;
CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS mart;

---------stage слой--------------------------------------------------------
---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS stage.super_store (
    row_id INT,
    order_uniq_card VARCHAR(20),
    order_date DATE,
    ship_date DATE,
    ship_mode VARCHAR(25),
    customer_uniq_card CHAR(8),
    customer_name VARCHAR(100),
    segment VARCHAR(100),
    country VARCHAR(100),
    city VARCHAR(100),
    _state VARCHAR(100),
    postal_code VARCHAR(5),
    region VARCHAR(100),
    product_uniq_card CHAR(15),
    category VARCHAR(100),
    sub_category VARCHAR(100),
    product_name VARCHAR(200),
    sales DECIMAL(10, 4),
    quantity INT,
    discount DECIMAL(3, 2),
    profit DECIMAL(10, 4)
);

---------core слой---------------------------------------------------------------

--------------------------------------------------
-- sales ->  orders 
--------------------------------------------------
CREATE TABLE IF NOT EXISTS core.orders (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_uniq_card VARCHAR(20),
    order_date DATE,
    ship_date DATE,
    ship_mode VARCHAR(25)
);


--------------------------------------------------
-- sales -> product_entities -> product_categories
--------------------------------------------------
CREATE TABLE IF NOT EXISTS core.product_categories (
    product_uniq_card CHAR(15),
    category VARCHAR(100),
    sub_category VARCHAR(100),
    PRIMARY KEY (product_uniq_card)
);



CREATE TABLE IF NOT EXISTS core.product_entities (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_uniq_card CHAR(15),
    product_name VARCHAR(150),
    sales DECIMAL(10, 4),
    quantity INT,
    --UNIQUE (product_uniq_card, product_name),
    CONSTRAINT fk_entity_category FOREIGN KEY (product_uniq_card) 
    REFERENCES core.product_categories(product_uniq_card) 
    ON DELETE SET NULL ON UPDATE CASCADE
);


------------------------------------------------------
-- sales -> customer_accounts -> [locations, customer]
------------------------------------------------------


CREATE TABLE IF NOT EXISTS core.locations (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country VARCHAR(100),
    city VARCHAR(100),
    _state VARCHAR(100),
    postal_code VARCHAR(5),
    region VARCHAR(100),
    UNIQUE (country, city, _state, postal_code, region)
);

CREATE TABLE IF NOT EXISTS core.customers (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_uniq_card CHAR(8),
    customer_name VARCHAR(100),
    segment VARCHAR(100),
    UNIQUE (customer_uniq_card, customer_name, segment)
);



CREATE TABLE IF NOT EXISTS core.customer_accounts (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT,
    location_id INT,
    is_active BOOLEAN DEFAULT TRUE,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customers_locations FOREIGN KEY (location_id) 
    REFERENCES core.locations(id) 
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_customers_account FOREIGN KEY (customer_id) 
    REFERENCES core.customers(id) 
    ON DELETE SET NULL ON UPDATE CASCADE
);

-----------------------------------------------------------
-- sales --------------------------------------------------
-----------------------------------------------------------

CREATE TABLE IF NOT EXISTS core.sales (
    sale_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT,
    active_customer_id INT,
    product_id INT,
    discount DECIMAL(3, 2),
    profit DECIMAL(10, 4),
    CONSTRAINT fk_sales_orders FOREIGN KEY (order_id) REFERENCES CORE.orders(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_sales_customers FOREIGN KEY (active_customer_id) REFERENCES CORE.customer_accounts(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_sales_products FOREIGN KEY (product_id) REFERENCES CORE.product_entities(id) ON DELETE SET NULL ON UPDATE CASCADE
);



---------mart слой---------------------------------------------------------
---------------------------------------------------------------------------

--денормализированная звезда
CREATE TABLE IF NOT EXISTS mart.fact_sales (
    sale_id INT,
    order_date DATE,
    ship_date DATE,
    ship_mode VARCHAR(25),
    customer_name VARCHAR(100),
    segment VARCHAR(100),
    country VARCHAR(100),
    city VARCHAR(100),
    _state VARCHAR(100),
    postal_code VARCHAR(5),
    region VARCHAR(100),
    category VARCHAR(100),
    sub_category VARCHAR(100),
    product_name VARCHAR(200),
    sales DECIMAL(10, 4),
    quantity INT,
    discount DECIMAL(3, 2),
    profit DECIMAL(10, 4)
);