drop table if exists students;
drop table if exists rooms;


create table rooms (
	rid int generated by default as identity (start with 0), 
	rname varchar
);

create table students (
	sid int generated by default as identity (start with 0),
	birthday timestamp,
	sname varchar,
	room int generated by default as identity (start with 0) references rooms(rid) ON DELETE CASCADE ON UPDATE CASCADE,
	sex char(1),
	check (sex in ('F', 'M'))
);


CREATE INDEX r_number ON students (room);